### ISSUE TITLE
Switch to using Needletail crate

### ISSUE THREAD

**Issue by juleskers** [OliPelz/fastq_extractor_proof_of_principle#6]
Needletail is a _zero-copy_ fastX reader crate.

You give it a filename and a record-handling callback function, and it does ALL the iteration.
It even avoids copies and allocations wherever possible, by taking reference to the input-file buffers 😲 
This could not have been closer to what we needed if we had written it ourselves 😄 

https://crates.io/crates/needletail
https://github.com/onecodex/needletail

**Comment by OliPelz** [comment]
Done! already merged in master branch.

**Comment by juleskers** [comment]
Nice! See commit ba8a0d0 !

I love how much clearer the iteration logic looks now.
